module.exports = {
  handleRegisterUser: require("./handleRegisterUser"),
  handleAuthenticateUser: require("./handleAuthenticateUser"),
  handleDeleteUser: require("./handleDeleteUser"),
  handleRetrieveUser: require("./handleRetrieveUser"),
  handleUpdateUser: require("./handleUpdateUser"),
  handleAddJob: require("./handleAddJob"),
  handleDeleteJob: require("./handleDeleteJob"),
  handleClockUserIn: require("./handleClockUserIn"),
  handleClockUserOut: require("./handleClockUserOut"),
  handleretrieveClockUser: require("./handleretrieveClockUser"),
  handleClockUserJobIn: require("./handleClockUserJobIn"),
  handleClockUserJobOut: require("./handleClockUserJobOut"),
  handleretrieveClockJob: require("./handleretrieveClockJob"),
  handleretrieveJobsUser: require("./handleretrieveJobsUser"),
  handleRetrieveJobs: require("./handleRetrieveJobs"),
  handleRetrieveUserRol: require("./handleRetrieveUserRol"),
  handleretrieveCloks: require("./handleretrieveCloks"),
  handleUpdateJob: require("./handleUpdateJob"),
};
