module.exports = {
    validateString: require('./validateString'),
    validateStringNotEmptyOrBlank: require('./validateStringNotEmptyOrBlank'),
    validateStringNotEmptyNoSpaces: require('./validateStringNotEmptyNoSpaces'),
    validateUsername: require('./validateUsername'),
    validateEmail: require('./validateEmail'),
    validatePassword: require('./validatePassword'),
    validateDate: require('./validateDate'),
    validateJWT: require('./validateJWT'),
    isValidJWT: require('./isValidJWT'),
    validateFunction: require('./validateFuncion'),
    validateObject: require('./validateObject'),
    validateNumber: require('./validateNumber'),
    validateCountryCode: require('./validateCountryCode'),
    validateArray: require('./validateArray'),
    validateGenres: require('./validateGenres'),
    validateDateOfBirth: require('./validateDateOfBirth'),
    validateInterpretationContent: require('./validateInterpretationContent'),
    validateRank: require('./validateRank'),
    validateFile: require('./validateFile'),
    validateCategory: require('./validateCategory')
}