import '../styles/globals.css'
import Head from 'next/head'

if (typeof XMLHttpRequest === 'undefined') {
  var XMLHttpRequest = require('xhr2');

  global.XMLHttpRequest = XMLHttpRequest
}

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>PitchUs</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="box-border w-full min-h-screen h-full bg-primary">
      <Component {...pageProps} />
    </div>
  </>
}

export default MyApp